---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-headless
  labels:
    app: "hello"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    helm.sh/release: "{{ .Release.Name }}"
    helm.sh/revision: "{{ .Release.Revision }}"
spec:
  ports:
    - name: 80-tcp
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: "hello"
    helm.sh/release: "{{ .Release.Name }}"
  clusterIP: None
status:
  loadBalancer: {}  
...